name: Deploy Kubernetes Infrastructure

on:
  push:
    branches:
      - main 

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install unzip, curl, and openssh-client
        run: |
          apt-get update
          apt-get install -y unzip curl openssh-client jq

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
    

      - name: Output IPs
        run: |
          echo "Master Public IP: $(terraform output master_public_ip)"
          echo "Worker Public IPs: $(terraform output worker_public_ips)"
